import { StyleSheet } from 'react-native';

export const C = {
  blue: '#2563eb',
  blueDark: '#1d4ed8',
  slate900: '#0f172a',
  slate700: '#334155',
  slate600: '#475569',
  slate500: '#64748b',
  slate400: '#94a3b8',
  slate300: '#cbd5e1',
  slate200: '#e2e8f0',
  slate100: '#f1f5f9',
  slate50: '#f8fafc',
  white: '#ffffff',
  green: '#059669',
  greenBg: '#ecfdf5',
  red: '#dc2626',
  redBg: '#fef2f2',
  amber: '#d97706',
  amberBg: '#fffbeb',
  purple: '#9333ea',
  purpleBg: '#faf5ff',
};

export const S = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.slate50 },
  screen: { flex: 1, backgroundColor: C.slate50 },
  content: { padding: 20, paddingBottom: 40 },
  title: { fontSize: 26, fontWeight: '800', color: C.slate900 },
  subtitle: { marginTop: 5, fontSize: 14, lineHeight: 21, color: C.slate500 },
  card: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.slate200,
    borderRadius: 16,
    padding: 16,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: C.slate300,
    borderRadius: 10,
    paddingHorizontal: 14,
    color: C.slate900,
    backgroundColor: C.white,
    fontSize: 15,
  },
  textarea: {
    minHeight: 90,
    borderWidth: 1,
    borderColor: C.slate300,
    borderRadius: 10,
    padding: 14,
    color: C.slate900,
    backgroundColor: C.white,
    fontSize: 15,
    textAlignVertical: 'top',
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: C.slate700,
    marginBottom: 7,
  },
  button: {
    minHeight: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  buttonText: { color: C.white, fontSize: 15, fontWeight: '700' },
  outlineButton: {
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.slate300,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  outlineText: { color: C.slate700, fontSize: 14, fontWeight: '700' },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: C.slate900 },
  muted: { color: C.slate500, fontSize: 13 },
});
